kind: Service
apiVersion: v1
metadata:
  name: gsp-vol-service
spec:
  type: NodePort
  selector:
    app: gsp-vol
  ports:
  - protocol: TCP
    port: 8080
    nodePort: 30100
    targetPort: 8080
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: gsp-vol
  labels:
    app: gsp-vol
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gsp-vol
  template:
    metadata:
      labels:
        app: gsp-vol
        version: "1.0.0-RELEASE"
    spec:
      containers:
      - name: gsp-vol
        image: docker.gsp.sicc.co.kr/vol:1.0.1-RELEASE
        env:
        - name: SPRING_PROFILES_ACTIVE
          value: prd
        - name: spring.cloud.config.uri
          value: http://100.70.69.238:8888
        ports:
        - name: http
          containerPort: 8080