kind: Service
apiVersion: v1
metadata:
  name: gsp-pot-service
spec:
  type: LoadBalancer
  selector:
    app: gsp-pot
  ports:
  - protocol: TCP
    port: 80
    nodePort: 30700
    targetPort: 8080
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: gsp-pot
  labels:
    app: gsp-pot
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gsp-pot
  template:
    metadata:
      labels:
        app: gsp-pot
        version: "1.0.1"
    spec:
      containers:
      - name: gsp-pot
        image: docker.gsp.sicc.co.kr/pot:1.0.1
        env:
        - name: SPRING_PROFILES_ACTIVE
          value: dev
        - name: spring.cloud.config.uri
          value: http://msa-config.development.svc.cluster.local:8888
        ports:
        - name: http
          containerPort: 8080