spring:
  devtools:
    livereload:
      enabled: true  # for jsp auto reload
    freemarker:
      cache: false
  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp
#  datasource:
#    type: org.apache.tomcat.jdbc.pool.DataSource
#    driverClassName: org.postgresql.Driver
#    url: jdbc:postgresql://localhost:5432/postgres?autoReconnect=true&useSSL=false
#    username: postgres
#    #password: ENC(2L3MvBFx+sCd0DQ79sMY6wR0bJvSGq3R)
#    password: New1234!
  datasource:
    type: org.springframework.jdbc.datasource.SimpleDriverDataSource
    driverClassName: com.microsoft.sqlserver.jdbc.SQLServerDriver
    url: jdbc:sqlserver://203.255.241.196:1433;DatabaseName=AG2018GMS
    username: siccgms    
    password: siccgms
#  datasource:
#    type: org.springframework.jdbc.datasource.SimpleDriverDataSource
#    driverClassName: com.microsoft.sqlserver.jdbc.SQLServerDriver
#    url: jdbc:postgresql://localhost:5432/postgres
#    username: postgres    
#    password: admin    
    
# LOGGING
#logging.config: classpath:logback/logback-spring.xml  # resource/logback-spring.xml에 위치하여 위치 자동 인식 


# Resource 영역 (addResourceHandlers) 
#server.compression: 
#    enabled: true
#    min-response-size: 2048
#spring.resources:
#    chain.cache: true 
#    chain.enabled: true
#    cache-period: 3600
#    static-locations: classpath:/static/

mybatis:
  mapper-locations: classpath:mappers/**/*.xml
  configuration:
    lazyLoadingEnabled: true
    aggressiveLazyLoading: false
    mapUnderscoreToCamelCase: true

server:
  port: 8090
  context-path: /
  jsp-servlet:
    init-parameters:
      developement: true # for jsp auto reload
  session :
    timeout: 30      
    
    

############################################################  
# context-core.xml
############################################################
settings:   
  SICC_SYSTEM: SVM
  SICC_CP: OLY
  SICC_SSO: false
  SICC_LOGIN_URL: /login  #SICC_LOGIN_URL: #{SICC_SSO?'/saml/login':'/login'}
  uploadPath: c:/gms/upload
  SICC_XSS_FILTER: true 

# MULTIPART (MultipartProperties)
spring.http.multipart:  
  enabled: true
  file-size-threshold: 0 
  location: /tmp
  max-file-size: 104857600KB 
  max-request-size: 104857600KB
  resolve-lazily: false
############################################################


############################################################  
# sicc.properties
############################################################  
sp:
  systemCd: EXP
  #sp.providerName=EXP_CMS
  providerName: BRP_WEB
  #sp.domain=http://local.pyeongchang2018.com:8080
  mainRedirect: /serviceprovider/sp/service_front
  createUrl: /saml/createrequestservlet
  logoutcreateUrl: /saml/createlogoutrequestservlet
  logoutUrl: /saml/logout
  acsUrl: /saml/acs
  #sp.publicKeyFilePath=/WEB-INF/cert/pubkey_share.der
  publicKeyFilePath: C:/sicc/gms_proj/gms2018/src/main/webapp/WEB-INF/cert/pubkey_share.der
  idpUrl: /identityprovider/saml/ProcessResponseServlet
  idpLogoutUrl: /common/login/logout
  editUser: /user/memberinfo/selectpopup?providerName=
  idpSessionStatusUrl: /identityprovider/saml/SessionStatusServlet
  #ip.domain=http://inp.pyeongchang2018.com:8888/sso
  domain: https://exp.pyeongchang2018.com:2443/sso/  
  DR: http://203.255.241.195:8888/sso
  secret: TheWinterIsComming
############################################################  
 
############################################################  
# email.properties
############################################################
mail: 
  smtp: 
    ip: http://203.224.137.53:8480/    
    host: cp-mail2018.asiangames2018.id
    port: 465
    user: noreply-volunteer@asiangames2018.id
    password: Success123!!
    fromEmail: noreply-volunteer@asiangames2018.id
    sender: 
      name: VOLUNTEER ASIAN GAMES 2018      
############################################################ 
